import { IsObject, IsOptional, IsString } from 'class-validator';

export class PostMessageDto {
  @IsOptional()
  @IsString()
  conversation_id?: string;

  @IsOptional()
  @IsString()
  student_id?: string;

  @IsString()
  body: string;

  /**
   * The exact MatchResult for the course this question is about (the
   * frontend's per-course "Ask AI" button already has it) — grounds the
   * answer in what was actually computed, including admission_eligibility,
   * instead of the assistant re-deriving eligibility from scratch by
   * name-matching the institution in `body`. Loosely typed here (same
   * pattern as RunMatchDto.weights) since it's always generated by our own
   * frontend, not raw external input; cast to MatchResult in the service.
   */
  @IsOptional()
  @IsObject()
  match_result?: Record<string, unknown>;
}
